#include<iostream>
using namespace std;
main(){
int a;
int b;
int c;
int d;
int e;
int f;
int g;
int h;
int i;
int j;
int k;
int l;
int m;
int n;
int o;
cout<<"Enter num 1:";
cin>>a;
cout<<"Enter num 2:";
cin>>b;
cout<<"Enter num 3:";
cin>>c;
cout<<"Enter num 4:";
cin>>d;
cout<<"Enter num 5:";
cin>>e;
cout<<"Enter num 6:";
cin>>f;
cout<<"Enter num 7:";
cin>>g;
cout<<"Enter num 8:";
cin>>h;
cout<<"Enter num 9:";
cin>>i;
cout<<"Enter num 10:";
cin>>j;
cout<<"Enter num 11:";
cin>>k;
cout<<"Enter num 12:";
cin>>l;
cout<<"Enter num 13:";
cin>>m;
cout<<"Enter num 14:";
cin>>n;
cout<<"Enter num 15:";
cin>>o;
int add;
int subtract;
int multiply;
add=a+b+c+d+e;
cout<<"Addition is:";
cout<<add;
multiply=f*g*h*i*j;
cout<<"Multiplication is:";
cout<<multiply;
subtract=k-l-m-n-o;
cout<<"Subtraction is:";
cout<<subtract;
int total;
total=(add+multiply)-subtract;
cout<<"Total is:";
cout<<total;
}